### ISSUE TITLE
Version 2.2.0 in Nixpkgs

### ISSUE THREAD

**Issue by aforemny** [alunduil/zfs-replicate#207]
Hi,

I am trying to use version 2.2.0 in Nixpkgs, but running `nix-build ./nix/default.nix` results for me in:
```
error: infinite recursion encountered

       at nixpkgs/pkgs/stdenv/generic/make-derivation.nix:347:7:

          346|       depsBuildBuild              = lib.elemAt (lib.elemAt dependencies 0) 0;
          347|       nativeBuildInputs           = lib.elemAt (lib.elemAt dependencies 0) 1;
             |       ^
          348|       depsBuildTarget             = lib.elemAt (lib.elemAt dependencies 0) 2;
(use '--show-trace' to show detailed location information)
```

My Nixpkgs is nixos-23.05, but I can reproduce it with nixos-22.05 as well. (Evaluation with nixos-22.11 seems to fail for an unrelated reason.)

I am not familiar with the Python ecosystem or poetry2nix, but I've found that removing `tool.poetry.group.dev.dependencies` from `pyproject.toml` and re-generating the `poetry.lock` makes the build work, but passing `groups = []` and `checkGroups = []` to `mkPoetryApplication` does not.

If you have any pointers on how I can use version 2.2.0 in Nixpkgs I would greatly appreciate it! Thanks!

**Comment by alunduil** [comment]
My first guess would be that I last generated that nix expression with poetry2nix quite some time ago.  Would you mind trying poetry2nix to regenerate `nix/default.nix`?  If that works, I'd love a pull request with an up-to-date Nix environment, as I don't use Nix right now, but I still love that ecosystem. Let me know if that makes sense or if you have any other questions.

**Comment by alunduil** [comment]
I'm looking at this again since it's been a long time, and I realised I needed to be corrected about generation using poetry2nix.  I'll peek at the documentation to see if a setting is missing, but I don't have an easy way to test this.  I'd appreciate a pull request if you could play with the derivation.

**Comment by alunduil** [comment]
@aforemny the infinite recursion you ran into came from a `nix/default.nix` generated a long time ago against a different poetry2nix, and the underlying problem is that nothing in that expression is pinned. #430 covers converting the build to a flake with pinned inputs so a nixpkgs bump stops re-breaking it. Marking this a duplicate of #430.
