### ISSUE TITLE
allow setting options on sends/recvs

### ISSUE THREAD

**Issue by prometheanfire** [alunduil/zfs-replicate#5]
zfs send -Lwecp -I ${SNAPSHOT}@${PREVIOUS_BACKUP_DATE} ${SNAPSHOT}@backup-${DATE} | pv -s "${SIZE}" | ssh 10.0.1.14 zfs recv -uvs storage-pool/remote-backups/${SNAPSHOT}

Sometimes it's useful to set things like the mountpoint or canmount or compression, etc on recv.  For sends it's useful for setting compression and the like (iirc Lwecp isn't supported everywhere).

**Comment by prometheanfire** [comment]
further, how I handle opportunistic encryption.

https://gist.github.com/prometheanfire/4483bcf7f4cadfc52c7c129e95e4a592

**Comment by alunduil** [comment]
@prometheanfire sorry this sat for years and then got closed by the stale bot rather than by any decision. The request ended up splitting in two: #392 covers tunable `zfs send` flags and #393 covers `zfs receive` flags plus setting properties on the receive side, which is the mountpoint and canmount case you described. Both have landed, in #462 and #455. There's also #391 for `--raw` on encrypted sends specifically. GitHub only lets me name one canonical duplicate so I've used #392, but #393 is the other half of this.
